name = "AdabTech"
license = "MIT"
licenselink = "https://github.com/adab-tech/adab-tech.github.io/blob/main/LICENSE"
description = "A clean, minimal theme for Adamu Abubakar's portfolio"
homepage = "https://adamu.tech"
tags = ["portfolio", "blog", "minimal", "responsive"]
features = ["responsive", "dark-mode", "multilingual"]
min_version = "0.121.0"

[author]
  name = "Adamu Abubakar"
  homepage = "https://adamu.tech"
